const { MongoClient, ObjectID } = require('mongodb');
console.log('stated file');

//Takes 2 arguments
//1- URL where the db lives
//2- callback function that fires after connect to the db. fail or success

//Adding
// MongoClient.connect('mongodb://localhost:27017/TodoApp', (err, database) => {
//     if(err)
//     {
//         throw new Error('Unable to connect to MongoDB');
//     }
//     let db = database.db('TodoApp');
//     try{
//         db.collection('Todos').insertOne({
//             text: 'Sleep',
//             completed: false
//         }, (err, result) => {
//             if(err){
//                 return console.log('Unable to insert todo', err);
//             }
//             console.log(JSON.stringify(result.ops, undefined, 2));
//         });
//     }catch(err)
//     {
//         console.log(`Something went wrong! ${err}`);
//     }
// });

//Fetch

// MongoClient.connect('mongodb://localhost:27017/TodoApp', (err, database) => {

//     if(err)
//     {
//         throw new Error('Unable to connect to MongoDB');
//     }
//     let db = database.db('TodoApp');
//     try{
//         //If I try to fetch Id like that Its not going to work, because the Id there is a ObjectID
//         //To fetch a ID generated by mongo its needed to create the OBJECTID
//         //For that require ojectId from mongo and pass the Id string.
//         // db.collection('Todos').find({_id: "5a48c20fab01b2112f6b83fe"}).toArray().then( data => {
//         //     console.log(JSON.stringify(data, undefined, 2));
//         // });

//         db.collection('Todos').find({_id: new ObjectID("5a48c20fab01b2112f6b83fe")}).toArray().then( data => {
//             console.log(JSON.stringify(data, undefined, 2));
//         });

//     }catch(err)
//     {
//         console.log(`Something went wrong! ${err}`);
//     }
// })

//Separating in functions

//connect ->
const getConnection = () => {
    return new Promise( (resolve, reject) => {
        MongoClient.connect('mongodb://localhost:27017/TodoApp', (err, database) => {
            if(err)
            {
                reject('Unable to connect to MongoDB');
            }
            console.log('Connected successfully!');
            resolve(database.db('TodoApp').collection);
        })
    });
    
}

//Add
const addRecord = async (collection, data) => {
    try{
        const con = await getConnection();
        con.collection(collection).insertOne(data, (err, result) => {
            if(err)
            {
                throw new Error('Unable to insert data');
            }
            console.log(`Data inserted: ${JSON.stringify(result.ops, undefined, 2)}`);
        });
    }catch(err)
    {
        console.log(`Something went wrong! ${err}`);
    }
}

//Fetch
const fetch = async(collection, where = "" ) =>
{
    try{
        const con = await getConnection();
        console.log(con);
        con(collection).find().then( data => {
            console.log(JSON.stringify(data, undefined, 2));
        });
    }catch(err)
    {
        console.log(`Something went wrong! ${err}`);
    }
}

fetch('Todos');
